{
 "title": "Infrastructure",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"bookinfo\", container!=\"\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"bookinfo\", resource=\"cpu\"}) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"bookinfo\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status & Restart",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"bookinfo\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}